### ISSUE TITLE
Copy values from SV Info tab?

### ISSUE THREAD

**Issue by JackLiberson** [kloi34/amoguSV#13]
Not certainly an issue, more like a request

When you hover over motion line it gives you two msx distances
Can you make that if you click on a section it will copy it value?
Like if I click LMB it will copy 6th _231_ msx and on RMB it will copy 7th _147.3_ msx like on a screenshot
![image](https://github.com/kloi34/amoguSV/assets/133762120/197d9913-81c6-443e-a121-309eb7190262)

It would be really helpful using it with vibrato with some exponential type

**Comment by kloi34** [comment]
This feature is too hard to implement for my small brain, so I made a jank "New All -w-" dropdown list that lets you copy values directly. This is added in amoguSV v6.6.1 which released just now. Let me know if that feature is sufficient for your needs or not.
